### ISSUE TITLE
Descending specificity error

### ISSUE THREAD

**Issue by paweljanuszkiewicz** [tonik/stylelint-config#3]
no-descending-specificity
Error for nested elements in changed scope:
![screen shot 2018-03-27 at 14 24 15](https://user-images.githubusercontent.com/22473415/37973092-0b2b129e-31da-11e8-89d0-1774d96a11dc.png)

**Comment by jedrzejchalubek** [comment]
Moved: https://github.com/tonik/stylelint-config-scss/issues/3
